# Generated by Django 4.2.23 on 2025-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
