# Generated by Django 4.2.23 on 2025-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_bill_stripe_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='health_resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
