# Generated by Django 4.2.23 on 2025-07-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_prescription_appointment_prescription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
