# Generated by Django 4.2.23 on 2025-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_bill_prescription_prescription_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
