# Generated by Django 4.2.23 on 2025-07-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_prescription_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='policy_number',
        ),
    ]
