# Generated by Django 4.2.23 on 2025-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_remove_bill_insurance_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
